### ISSUE TITLE
Build fails on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by mvglasow** [NeuronRobotics/nrjavaserial#103]
I just tried to build on Ubuntu 16.04 and got the following error:

```
src/SerialImp.c:147:21: fatal error: lockdev.h: No such file or directory
compilation terminated.
Makefile:150: recipe for target 'linux64' failed
make[1]: *** [linux64] Error 1
make[1]: Leaving directory '/home/michael/src/nrjavaserial/src/main/c'
Makefile:17: recipe for target 'linux64' failed
make: *** [linux64] Error 2
```

According to https://github.com/emericg/SmartServoFramework/issues/14, `liblockdev` got removed from Ubuntu. A workaround is to install the Trusty (14.04) package, but this is probably not a long-term solution.

SmartServoFramework has since dropped the dependency, and so have others (e.g. https://github.com/Pulse-Eight/libcec/commit/ff86c07a16a6a05be936b27e3f390b61f2ba4d2b).

**Comment by madhephaestus** [comment]
the build has been updated
